CREATE TABLE IF NOT EXISTS TB_PESSOA (
    PESSOA_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    TELEFONE VARCHAR(14),
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT now(),
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT now()
);