CREATE TABLE IF NOT EXISTS TB_ESTADO (
    ESTADO_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME CHAR(2) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT now(),
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO TB_ESTADO(NOME) VALUES ("AC");
INSERT INTO TB_ESTADO(NOME) VALUES ("AL");
INSERT INTO TB_ESTADO(NOME) VALUES ("AP");
INSERT INTO TB_ESTADO(NOME) VALUES ("AM");
INSERT INTO TB_ESTADO(NOME) VALUES ("BA");
INSERT INTO TB_ESTADO(NOME) VALUES ("CE");
INSERT INTO TB_ESTADO(NOME) VALUES ("DF");
INSERT INTO TB_ESTADO(NOME) VALUES ("ES");
INSERT INTO TB_ESTADO(NOME) VALUES ("GO");
INSERT INTO TB_ESTADO(NOME) VALUES ("MA");
INSERT INTO TB_ESTADO(NOME) VALUES ("MT");
INSERT INTO TB_ESTADO(NOME) VALUES ("MS");
INSERT INTO TB_ESTADO(NOME) VALUES ("MG");
INSERT INTO TB_ESTADO(NOME) VALUES ("PA");
INSERT INTO TB_ESTADO(NOME) VALUES ("PB");
INSERT INTO TB_ESTADO(NOME) VALUES ("PR");
INSERT INTO TB_ESTADO(NOME) VALUES ("PE");
INSERT INTO TB_ESTADO(NOME) VALUES ("PI");
INSERT INTO TB_ESTADO(NOME) VALUES ("RJ");
INSERT INTO TB_ESTADO(NOME) VALUES ("RN");
INSERT INTO TB_ESTADO(NOME) VALUES ("RS");
INSERT INTO TB_ESTADO(NOME) VALUES ("RO");
INSERT INTO TB_ESTADO(NOME) VALUES ("RR");
INSERT INTO TB_ESTADO(NOME) VALUES ("SC");
INSERT INTO TB_ESTADO(NOME) VALUES ("SP");
INSERT INTO TB_ESTADO(NOME) VALUES ("SE");
INSERT INTO TB_ESTADO(NOME) VALUES ("TO");