CREATE TABLE IF NOT EXISTS TB_ESTADO (
    ESTADO_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME CHAR(2) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT now(),
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT now()
);