CREATE TABLE IF NOT EXISTS TB_ENDERECO (
    ENDERECO_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    PESSOA_ID INT NOT NULL,
    ESTADO_ID INT NOT NULL,
    LOGRADOURO VARCHAR(500) NOT NULL,
    NUMERO INTEGER NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    COMPLEMENTO VARCHAR(500),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT now(),
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT FOREIGN KEY(PESSOA_ID) REFERENCES TB_PESSOA(PESSOA_ID),
    CONSTRAINT FOREIGN KEY(ESTADO_ID) REFERENCES TB_ESTADO(ESTADO_ID)
);